danliris/dl-ui

src/components/form/auto-suggests/vat-auto-suggest.js
src/components/form/index.js
src/components/react/auto-suggests/vat-auto-suggest-react.jsx
src/components/react/po-external/po-external-item-collection-react.jsx
src/components/react/po-external/po-external-item-react.jsx
src/components/react/po-external/po-item-react.jsx
src/modules/purchasing/monitoring-delivery-order/list.html
src/modules/purchasing/monitoring-purchase-order/list.html
src/modules/purchasing/purchase-order-external/data-form.html
src/modules/purchasing/purchase-order-external/data-form.js
src/modules/purchasing/purchase-order-external/list.html

1. Pindahkan kolom konversi
2. make thousand separator
3. change label cari nomor become cari
3. make vat autosuggest

done some feedback 

---

src/modules/production/finishing-printing/reports/monitoring-event-report/index.html
src/modules/production/finishing-printing/reports/monitoring-event-report/index.js
src/modules/production/finishing-printing/reports/monitoring-event-report/list.html
src/modules/production/finishing-printing/reports/monitoring-event-report/list.js
src/modules/production/finishing-printing/reports/monitoring-event-report/service.js
src/routes/production.js

add monitoring-event-report

---

src/modules/production/finishing-printing/monitoring-event/data-form.js

fix empty color when create monitoringEvent

fix empty color when create monitoringEvent

---

src/modules/master/machine-type/edit.js
src/modules/master/machine-type/service.js
src/modules/production/finishing-printing/monitoring-specification-machine/create.html
src/modules/production/finishing-printing/monitoring-specification-machine/create.js
src/modules/production/finishing-printing/monitoring-specification-machine/data-form.html
src/modules/production/finishing-printing/monitoring-specification-machine/edit.html
src/modules/production/finishing-printing/monitoring-specification-machine/edit.js
src/modules/production/finishing-printing/monitoring-specification-machine/service.js
src/modules/production/finishing-printing/monitoring-specification-machine/view.html

bug fixed edit,
add edit monitoring spec machine

monitoring spec machine. machine type

---

src/modules/production/finishing-printing/kanban/data-form.html

fix kanban table element typo

---

src/modules/production/finishing-printing/kanban/data-form.html
src/modules/production/finishing-printing/kanban/edit.js
src/modules/sales/production-order/templates/lamp-standard.js

- show color in view, fix color default value in edit
- fix productionOrder lampStandardId

fix color data binding in edit & view

---

src/components/customs/auto-suggests/react/category-auto-suggest-react.jsx
src/modules/purchasing/monitoring-purchase-order-all-user/list.html
src/modules/purchasing/monitoring-purchase-order/list.html
src/routes/master.js

1. Kode Kategori dimunculkan saat input PR
2. Monitoring purchase ditambah 2 kolom ‘tempo pembayaran’ dari PO Eksternal dan diletakkan di belakang kolom bon penerimaan
3. Master Supplier dapat di akses Kasie untuk Create Update delete

Fix feedback

---

src/au-components/form/_layout.js
src/modules/production/finishing-printing/kanban/template/step-item.html
src/modules/production/finishing-printing/kanban/template/step-item.js

fix step item data bind, remove unnecessary console log

fix step item data bind

---

src/modules/production/finishing-printing/monitoring-event/data-form.js
src/utils/moment-to-millis.js

- adjust TimeInMillis using moment format 'x'
- fix productionOrderId is not updated onChange
- fix selectedProductionOrderDetail is not mapped properly into colorRequest
- fix momentInMillis utility using moment format 'x'
- fix dateStart & dateEnd initial state in edit to be validated properly in monitoring-event-manager

fix monitoringEvent

---

src/modules/production/finishing-printing/kanban/edit.js
src/modules/production/finishing-printing/monitoring-event/create.html
src/modules/production/finishing-printing/monitoring-event/data-form.html
src/modules/production/finishing-printing/monitoring-event/data-form.js
src/modules/production/finishing-printing/monitoring-event/edit.html
src/modules/production/finishing-printing/monitoring-event/edit.js
src/modules/production/finishing-printing/monitoring-event/list.html
src/modules/production/finishing-printing/monitoring-event/list.js
src/modules/production/finishing-printing/monitoring-event/view.html
src/modules/production/finishing-printing/monitoring-event/view.js
src/modules/production/finishing-printing/reports/monitoring-event-report/list.html

fix monitoringEvent dateTimeEnd
fix monitoringEvent & report language

fix monitoringEvent dateTimeEnd

---

src/modules/production/finishing-printing/monitoring-event/data-form.js
src/modules/production/finishing-printing/monitoring-event/list.js

fix monitoringEvent date wrong value
fix monitoringEvent list date format

fix monitoringEvent list date

---

src/components/customs/auto-suggests/machine-auto-suggest.js
src/components/customs/collections/machine-type/machine-type-indicator-collection-react.jsx
src/components/customs/collections/machine-type/machine-type-indicator-collection.js
src/components/customs/collections/machine-type/machine-type-indicator-react.jsx
src/components/customs/collections/monitoring-specification-machine/monitoring-specification-machine-collection-react.jsx
src/components/customs/collections/monitoring-specification-machine/monitoring-specification-machine-collection.js
src/components/customs/collections/monitoring-specification-machine/monitoring-specification-machine-react.jsx
src/modules/master/machine-type/data-form.html
src/modules/production/finishing-printing/monitoring-specification-machine/data-form.html
src/modules/production/finishing-printing/monitoring-specification-machine/data-form.js
src/modules/production/finishing-printing/monitoring-specification-machine/edit.js

mon spec machine. machine type

mon spec machine. machine type

---

src/modules/production/finishing-printing/monitoring-specification-machine/data-form.js
src/modules/production/finishing-printing/reports/monitoring-specification-machine-report/list.html
src/modules/production/finishing-printing/reports/monitoring-specification-machine-report/list.js
src/modules/production/finishing-printing/reports/monitoring-specification-machine-report/service.js
src/routes/production.js

update report monitoring spec machine

update report monitoring spec machine

---

src/components/form/basic/react/numeric-react.jsx

fix numeric react cannot  be used inside collection

fix numeric react

---

src/components/customs/collections/monitoring-specification-machine/monitoring-specification-machine-collection-react.jsx
src/components/customs/collections/monitoring-specification-machine/monitoring-specification-machine-react.jsx
src/routes/production.js

update mon spec machine react

---

src/loader/machine-loader.js
src/modules/production/finishing-printing/monitoring-specification-machine/data-form.html
src/modules/production/finishing-printing/monitoring-specification-machine/data-form.js
src/modules/production/finishing-printing/monitoring-specification-machine2/template/monitoring-specification-machine-item.html
src/modules/production/finishing-printing/monitoring-specification-machine2/template/monitoring-specification-machine-item.js
src/modules/production/finishing-printing/reports/monitoring-specification-machine-report/list.js
src/routes/production.js

update mon spec machine

---

src/modules/production/finishing-printing/monitoring-specification-machine/data-form.html
src/modules/production/finishing-printing/monitoring-specification-machine/data-form.js

monitoring specification machine

---

src/routes/master.js

machine type

---

src/loader/account-banks-loader.js
src/modules/sales/weaving-sales-contract/create.html
src/modules/sales/weaving-sales-contract/create.js
src/modules/sales/weaving-sales-contract/data-form.html
src/modules/sales/weaving-sales-contract/data-form.js
src/modules/sales/weaving-sales-contract/edit.html
src/modules/sales/weaving-sales-contract/edit.js
src/modules/sales/weaving-sales-contract/view.html

update loader account bank, add sales contract-weaving

update loader account bank, add sales contract-weaving

---

src/modules/master/machine/create.html
src/modules/master/machine/create.js
src/modules/master/machine/data-form.html
src/modules/master/machine/data-form.js
src/modules/master/machine/edit.html
src/modules/master/machine/edit.js
src/modules/master/machine/view.html
src/modules/master/machine/view.js
src/modules/production/finishing-printing/kanban/create.html
src/modules/production/finishing-printing/kanban/create.js
src/modules/production/finishing-printing/kanban/data-form.html
src/modules/production/finishing-printing/kanban/data-form.js
src/modules/production/finishing-printing/kanban/edit.html
src/modules/production/finishing-printing/kanban/edit.js
src/modules/production/finishing-printing/kanban/view.html
src/modules/production/finishing-printing/kanban/view.js

update crud button binding in au-input-form
- master machine
- production finishing printing kanban

update crud button binding in au-input-form

---

src/modules/master/machine/data-form.html
src/modules/production/finishing-printing/kanban/data-form.html
src/modules/production/finishing-printing/kanban/data-form.js

- master machine remove unnecessary btn-group class in slot actions
- update kanban CRUD button using options object

update kanban au-input-form

---

src/loader/term-of-payment-loader.js
src/modules/sales/weaving-sales-contract/create.html
src/modules/sales/weaving-sales-contract/create.js
src/modules/sales/weaving-sales-contract/data-form.html
src/modules/sales/weaving-sales-contract/data-form.js
src/modules/sales/weaving-sales-contract/edit.html
src/modules/sales/weaving-sales-contract/edit.js
src/modules/sales/weaving-sales-contract/list.html
src/modules/sales/weaving-sales-contract/list.js
src/modules/sales/weaving-sales-contract/service.js
src/modules/sales/weaving-sales-contract/view.html
src/modules/sales/weaving-sales-contract/view.js

weaving sales contract

---

src/modules/sales/weaving-sales-contract/data-form.js

update weaving sales contract

---

src/modules/production/finishing-printing/monitoring-specification-machine/create.js

update monitoring spec machine

update monitoring spec machine

---

src/loader/weaving-sales-contract-loader.js
src/modules/sales/reports/weaving-sales-contract-report/index.html
src/modules/sales/reports/weaving-sales-contract-report/index.js
src/modules/sales/reports/weaving-sales-contract-report/list.html
src/modules/sales/reports/weaving-sales-contract-report/list.js
src/modules/sales/reports/weaving-sales-contract-report/service.js
src/routes/sales.js

weaving sales contract report

---

src/modules/sales/reports/weaving-sales-contract-report/list.html
src/modules/sales/reports/weaving-sales-contract-report/list.js

update weaving sales contract report fix final

update weaving sales contract report fix final

---

src/modules/sales/reports/weaving-sales-contract-report/list.js

update weaving sales contract report

update weaving sales contract report

---

src/loader/packing-loader.js
src/modules/production/finishing-printing/reports/packing-report/index.html
src/modules/production/finishing-printing/reports/packing-report/index.js
src/modules/production/finishing-printing/reports/packing-report/list.html
src/modules/production/finishing-printing/reports/packing-report/list.js
src/modules/production/finishing-printing/reports/packing-report/service.js
src/routes/production.js

report packing

---

src/utils/rest-service.js

update rest service

---

src/modules/master/product-budgeting/upload.js

update product buget upload

---

src/main.js
src/modules/production/finishing-printing/inspection-lot-color/create.js
src/modules/production/finishing-printing/kanban/create.js
src/modules/production/finishing-printing/monitoring-event/create.js
src/modules/production/finishing-printing/monitoring-specification-machine/create.js
src/modules/production/finishing-printing/packing/create.js
src/modules/production/finishing-printing/quality-control/defect/create.js
src/modules/production/spinning/winding/winding-production-output/create.js
src/modules/production/spinning/winding/winding-quality-sampling/create.js
src/modules/purchasing/delivery-order/create.js
src/modules/purchasing/purchase-order-external/create.js
src/modules/purchasing/purchase-order/create.html
src/modules/purchasing/purchase-order/create.js
src/modules/purchasing/purchase-request/create.js
src/modules/purchasing/unit-payment-order/create.js
src/modules/purchasing/unit-payment-price-correction-note/create.js
src/modules/purchasing/unit-payment-quantity-correction-note/create.js
src/modules/purchasing/unit-receipt-note/create.js
src/modules/sales/finishing-printing-sales-contract/create.js
src/modules/sales/production-order/create.js
src/modules/sales/spinning-sales-contract/create.js
src/modules/sales/weaving-sales-contract/create.js

create form:navigate route  to create with activationStrategy

update ui create form. production,sales,purchasing

---

src/modules/master/instruksi/create.js

add create js

---

package.json
src/modules/production/finishing-printing/inspection-lot-color/create.js
src/modules/production/finishing-printing/kanban/create.js
src/modules/production/finishing-printing/monitoring-event/create.js
src/modules/production/finishing-printing/monitoring-specification-machine/create.js
src/modules/production/finishing-printing/packing/create.js
src/modules/production/finishing-printing/quality-control/defect/create.js
src/modules/production/spinning/winding/winding-production-output/create.js
src/modules/production/spinning/winding/winding-quality-sampling/create.js
src/modules/purchasing/delivery-order/create.js
src/modules/purchasing/monitoring-purchase-request-all-unit/list.js
src/modules/purchasing/monitoring-purchase-request/list.js
src/modules/purchasing/purchase-order-external/create.js
src/modules/purchasing/purchase-order/create.js
src/modules/purchasing/purchase-request/create.js
src/modules/purchasing/unit-payment-order/create.js
src/modules/purchasing/unit-payment-price-correction-note/create.js
src/modules/purchasing/unit-payment-quantity-correction-note/create.js
src/modules/purchasing/unit-receipt-note/create.js
src/modules/sales/finishing-printing-sales-contract/create.js
src/modules/sales/production-order/create.js
src/modules/sales/spinning-sales-contract/create.js
src/modules/sales/weaving-sales-contract/create.js

update ui create form

---

src/modules/production/finishing-printing/monitoring-specification-machine/create.js
src/modules/production/finishing-printing/monitoring-specification-machine/data-form.html
src/modules/production/finishing-printing/monitoring-specification-machine/data-form.js

update monitoring specification machine

update monitoring specification machine

---

src/modules/purchasing/koreksi-harga/index.html
src/modules/purchasing/koreksi-harga/index.js
src/modules/purchasing/koreksi-harga/list.html
src/modules/purchasing/koreksi-harga/list.js
src/modules/purchasing/koreksi-harga/service.js
src/routes/purchasing.js

add menu report

---

src/modules/production/finishing-printing/reports/bad-output-report/index.html
src/modules/production/finishing-printing/reports/bad-output-report/index.js
src/modules/production/finishing-printing/reports/bad-output-report/list.html
src/modules/production/finishing-printing/reports/bad-output-report/list.js
src/modules/production/finishing-printing/reports/bad-output-report/service.js
src/routes/production.js

Pemintaan untuk update menu dan halaman untuk report bad/good output agar bisa ditambahkan ke halaman website diatas

update menu bad-ouput-report

---

src/main.js
src/routes/purchasing.js

tambah routes

---

src/modules/power-bi/finishing-printing/list.js
src/modules/production/finishing-printing/monitoring-event/data-form.html
src/modules/production/finishing-printing/monitoring-event/data-form.js
src/modules/production/finishing-printing/monitoring-event/list.html
src/modules/production/finishing-printing/monitoring-event/list.js

update module monitoring event, power bi finishing printing

update module monitoring event, power bi finishing printing

---

src/loader/product-name-loader.js
src/modules/purchasing/monitoring-price/index.html
src/modules/purchasing/monitoring-price/index.js
src/modules/purchasing/monitoring-price/list.html
src/modules/purchasing/monitoring-price/list.js
src/modules/purchasing/monitoring-price/service.js
src/routes/purchasing.js

penambahan menu untuk memonitor history harga barang

Tambah menu history harga barang

---

src/modules/production/finishing-printing/monitoring-specification-machine/create.js
src/modules/production/finishing-printing/monitoring-specification-machine/data-form.html
src/modules/production/finishing-printing/monitoring-specification-machine/data-form.js
src/modules/production/finishing-printing/monitoring-specification-machine/edit.html
src/modules/production/finishing-printing/monitoring-specification-machine/edit.js
src/modules/production/finishing-printing/monitoring-specification-machine/list.html
src/modules/production/finishing-printing/monitoring-specification-machine/list.js
src/modules/production/finishing-printing/monitoring-specification-machine/view.html
src/modules/production/finishing-printing/monitoring-specification-machine/view.js

update monitorin gspecification machine

update monitorin gspecification machine

---

src/routes/purchasing.js

add user access

---

src/routes/purchasing.js

revisi hak akses monitoring koreksi jumlah

revisi hak akses

---

src/modules/purchasing/monitoring-correction-quantity/list.html

revisi kolom

---

src/modules/production/finishing-printing/reports/bad-output-report/list.html

mengubah tampilan good/bad report pada sisi no order dihilangkan hanya berdasarkan mesin

Mengubah Tampilan form good/bad report

---

src/modules/sales/reports/sales-monthly-report/index.html
src/modules/sales/reports/sales-monthly-report/index.js
src/modules/sales/reports/sales-monthly-report/list.html
src/modules/sales/reports/sales-monthly-report/list.js
src/modules/sales/reports/sales-monthly-report/service.js
src/routes/sales.js

add module report sales

---

src/main.js
src/modules/purchasing/monitoring-purchase-order-internal/list.html
src/routes/purchasing.js

Nambah Filter

---

src/modules/purchasing/monitoring-price/list.html

ganti judul

---

src/main.js
src/modules/purchasing/reports/bon-unit-blm-spb/list.html
src/modules/purchasing/reports/bon-unit-blm-spb/list.js
src/modules/purchasing/reports/bon-unit-blm-spb/service.js

edit list.js list.html service.js

edit list.js list.html service.js

---

src/modules/sales/reports/sales-monthly-report/list.html
src/modules/sales/reports/sales-monthly-report/list.js

tambah filter berdasarkan account

update laporan sales per bulan

---

src/main.js
src/modules/purchasing/monitoring-purchase-order-internal/list.html
src/modules/purchasing/monitoring-purchase-order-internal/list.js

Rubah kolom

---

src/modules/purchasing/koreksi-harga/index.js
src/modules/purchasing/koreksi-harga/list.html
src/modules/purchasing/koreksi-harga/list.js
src/modules/purchasing/koreksi-harga/service.js

update list.html, list.js

---

src/modules/power-bi/purchasing/list.js

List Top Pembelian per Kategori

Add List Report

---

src/modules/power-bi/purchasing/list.js

Change Dashboard's Name

---

src/modules/power-bi/purchasing/list.js

add menu powerbi durasi bon terima unit - surat perintah bayar

add menu powerbi

---

src/modules/purchasing/monitoring-purchase-order-all-user/list.html
src/modules/purchasing/monitoring-purchase-order/list.html

Update UI Monitoring Purchase All & By User

Update UI Monitoring Purchase

---

src/modules/purchasing/monitoring-purchase-request/list.html
src/modules/purchasing/monitoring-purchase-request/list.js

Tanggal Diminta Datang PO Eksternal

Add Column

---

src/modules/purchasing/reports/purchase-order-report/staff-report/index.html
src/modules/purchasing/reports/purchase-order-report/staff-report/index.js
src/modules/purchasing/reports/purchase-order-report/staff-report/list.html
src/modules/purchasing/reports/purchase-order-report/staff-report/list.js
src/modules/purchasing/reports/purchase-order-report/staff-report/service.js
src/modules/purchasing/reports/purchase-order-report/staff-report/view.html
src/modules/purchasing/reports/purchase-order-report/staff-report/view.js
src/routes/purchasing.js

Menambahkan menu ketepatan staff dan halaman laporan ketepatan staff

Tambah Menu Ketepatan Staff

---

src/modules/garment-purchasing/etl/garment-purchase-requests/migrate.js

remove debugger

---

src/modules/purchasing/monitoring-purchase-order-all-user/list.html
src/modules/purchasing/monitoring-purchase-order/list.html

Update Module Monitoring Purchase - All & By User

Update Module Monitoring Purchase

---

src/loader/garment-purchase-orders-loader.js
src/loader/garment-unit-loader.js
src/modules/garment-purchasing/monitoring-purchase-order-internal/index.html
src/modules/garment-purchasing/monitoring-purchase-order-internal/index.js
src/modules/garment-purchasing/monitoring-purchase-order-internal/list.html
src/modules/garment-purchasing/monitoring-purchase-order-internal/list.js
src/modules/garment-purchasing/monitoring-purchase-order-internal/service.js
src/routes/garment-purchasing.js

monitoring purchase orders internal report

monitoring purchase orders internal report

---

src/modules/garment-purchasing/monitoring-purchase-order-internal/list.html
src/modules/garment-purchasing/monitoring-purchase-order-internal/list.js

update ui monitoring garment purchase orders

update ui monitoring garment purchase orders

---

src/routes/purchasing.js

Hapus menu

---

src/main.js
src/modules/garment-purchasing/garment-currency/data-form.html
src/modules/garment-purchasing/garment-currency/data-form.js
src/modules/garment-purchasing/garment-currency/edit.html
src/modules/garment-purchasing/garment-currency/edit.js
src/modules/garment-purchasing/garment-currency/index.html
src/modules/garment-purchasing/garment-currency/index.js
src/modules/garment-purchasing/garment-currency/list.html
src/modules/garment-purchasing/garment-currency/list.js
src/modules/garment-purchasing/garment-currency/service.js
src/modules/garment-purchasing/garment-currency/upload.html
src/modules/garment-purchasing/garment-currency/upload.js
src/modules/garment-purchasing/garment-currency/view.html
src/modules/garment-purchasing/garment-currency/view.js
src/routes/garment-purchasing.js

garment currency

---

src/modules/purchasing/reports/purchase-order-report/staff-report/list.html
src/modules/purchasing/reports/purchase-order-report/staff-report/list.js
src/modules/purchasing/reports/purchase-order-report/staff-report/service.js
src/modules/purchasing/reports/purchase-order-report/staff-report/view.html
src/modules/purchasing/reports/purchase-order-report/staff-report/view.js

Update UI ketepatan staff

---

src/routes/garment-purchasing.js
src/routes/master.js

update garment purchasing group routes

update garment purchasing group routes

---

src/modules/purchasing/reports/purchase-order-report/staff-report/view.html

menambahkan field untuk staff report detail nama barang dan nama supplier

menambah field

---

src/modules/garment-purchasing/garment-currency/data-form.html
src/modules/garment-purchasing/garment-currency/data-form.js
src/modules/garment-purchasing/garment-currency/edit.js
src/routes/garment-purchasing.js

update ui garment currency

---

src/modules/garment-purchasing/garment-currency/edit.html
src/modules/garment-purchasing/garment-currency/list.html
src/modules/garment-purchasing/garment-currency/upload.html
src/modules/garment-purchasing/garment-currency/view.html
src/routes/master.js

update naming garment currency

update naming garment currency

---

src/modules/garment-purchasing/etl/garment-purchase-requests/migrate.js
src/modules/garment-purchasing/garment-currency/upload.js

update garment etl ui

---

src/modules/garment-purchasing/etl/garment-purchase-requests/migrate.html
src/modules/garment-purchasing/etl/garment-purchase-requests/migrate.js

update ui gra,ment purchase

---

src/modules/garment-purchasing/garment-currency/upload.js

garment etl

---

src/modules/purchasing/reports/purchase-order-report/staff-report/view.html
src/modules/purchasing/reports/purchase-order-report/staff-report/view.js

revisi untuk ubah tampilan menu ketepatan kedatangan barang

revisi UI ketepatan kedatangan barang

---

src/modules/master/storage/create.html
src/modules/master/storage/create.js
src/modules/master/storage/data-form.html
src/modules/master/storage/data-form.js
src/modules/master/storage/edit.html
src/modules/master/storage/edit.js
src/modules/master/storage/index.html
src/modules/master/storage/index.js
src/modules/master/storage/list.html
src/modules/master/storage/list.js
src/modules/master/storage/service.js
src/modules/master/storage/view.html
src/modules/master/storage/view.js
src/routes/master.js

master storage module

---

src/modules/purchasing/reports/purchase-order-report/staff-report/view.html
src/modules/purchasing/reports/purchase-order-report/staff-report/view.js

Merubah view tanggal sesuai dengan permintaan user

Merubah model tanggal

---

src/modules/production/finishing-printing/monitoring-kanban/list.html
src/modules/production/finishing-printing/monitoring-kanban/list.js
src/modules/production/finishing-printing/monitoring-kanban/service.js

menambah filter monitoring kanban untuk filter reproses

menambah filter monitoring kanban

---

src/modules/power-bi/purchasing-textile/list.js

nambah menu

---

src/modules/power-bi/purchasing-textile/list.js

rubah nama menu

---

src/modules/power-bi/dealtracking/index.html
src/modules/power-bi/dealtracking/index.js
src/modules/power-bi/dealtracking/list.html
src/modules/power-bi/dealtracking/list.js
src/modules/power-bi/dealtracking/service.js
src/modules/power-bi/dealtracking/view.html
src/modules/power-bi/dealtracking/view.js
src/routes/report.js

Menambah Menu Report Dasbord untuk Deal Tracking agar bisa diakses untuk penjualan

Menambah Menu Report Dasbord

---

src/modules/migration-log/monitoring-migration-log/index.html
src/modules/migration-log/monitoring-migration-log/index.js
src/modules/migration-log/monitoring-migration-log/list.html
src/modules/migration-log/monitoring-migration-log/list.js
src/modules/migration-log/monitoring-migration-log/service.js
src/routes/index.js
src/routes/migration-log.js

migration log

---

src/loader/unit-payment-orders-loader.js
src/modules/purchasing/monitoring-surat-perintah-bayar/index.html
src/modules/purchasing/monitoring-surat-perintah-bayar/index.js
src/modules/purchasing/monitoring-surat-perintah-bayar/list.html
src/modules/purchasing/monitoring-surat-perintah-bayar/list.js
src/modules/purchasing/monitoring-surat-perintah-bayar/service.js
src/routes/purchasing.js

Menambahkan menu monitoring Surat Perintah Bayar dengan menambah loader no Unit payment order

Menambah menu Monitoring SPB

---

src/modules/purchasing/monitoring-surat-perintah-bayar/list.html

menambah tampilan kolom untuk menu monitoring SPB

Tambah Kolom ( Monitoring SPB )

---

src/modules/sales/reports/production-order-report/list.js
src/modules/sales/reports/production-order-report/service.js

ubah export to excel  menu monitoring surat perintah produksi

ubah export to excel

---

src/modules/garment-purchasing/etl/garment-purchase-requests/migrate.js

update page size

---

src/modules/garment-purchasing/etl/garment-purchase-requests/migrate.js

update etl ui

---

src/modules/garment-purchasing/etl/garment-purchase-requests/list.js
src/modules/garment-purchasing/etl/garment-purchase-requests/migrate.html
src/modules/garment-purchasing/etl/garment-purchase-requests/migrate.js
src/modules/garment-purchasing/etl/garment-purchase-requests/service.js

update etl purchase request garment

update etl purchase request garment

---

src/modules/garment-purchasing/garment-generating-data/service.js

Update Module Generate Data (Service Nota Koreksi)

Update Module UI

---

src/modules/purchasing/monitoring-purchase-order-internal/list.html
src/modules/purchasing/monitoring-purchase-order-internal/list.js
src/modules/purchasing/monitoring-purchase-order-internal/service.js

Menambah Filter staff pembelian

Tambah Filter

---

src/modules/purchasing/monitoring-surat-perintah-bayar/list.html
src/modules/purchasing/monitoring-surat-perintah-bayar/list.js

Update tampilan Menu Monitoring SPB untuk list.html dan list.jsnya

Update tampilan Menu Monitoring SPB

---

src/modules/production/finishing-printing/reports/daily-operation-machine/index.html
src/modules/production/finishing-printing/reports/daily-operation-machine/index.js
src/modules/production/finishing-printing/reports/daily-operation-machine/list.html
src/modules/production/finishing-printing/reports/daily-operation-machine/list.js
src/modules/production/finishing-printing/reports/daily-operation-machine/service.js
src/routes/production.js

ui daily machine report

---

src/modules/purchasing/unit-receipt-note-monitoring/list.html
src/modules/purchasing/unit-receipt-note-monitoring/list.js
src/modules/purchasing/unit-receipt-note-monitoring/service.js

Add Filter

---

src/modules/power-bi/finishing-printing/list.js
src/modules/production/finishing-printing/reports/bad-output-report/list.html

update good bad output report

---

src/modules/production/finishing-printing/reports/packing-report/list.html
src/modules/production/finishing-printing/reports/packing-report/list.js
src/modules/production/finishing-printing/reports/qcgudang-report/index.html
src/modules/production/finishing-printing/reports/qcgudang-report/index.js
src/modules/production/finishing-printing/reports/qcgudang-report/list.html
src/modules/production/finishing-printing/reports/qcgudang-report/list.js
src/modules/production/finishing-printing/reports/qcgudang-report/service.js
src/routes/production.js

Menambah Menu Laporan Penyerahan QC ke Gudang dan menyesuaikan ke service API nya

Menambah Menu Laporan Penyerahan QC ke Gudang

---

src/modules/inventory/reports/fp-shiptment-delivery-buyer-report/index.html
src/modules/inventory/reports/fp-shiptment-delivery-buyer-report/index.js
src/modules/inventory/reports/fp-shiptment-delivery-buyer-report/list.html
src/modules/inventory/reports/fp-shiptment-delivery-buyer-report/list.js
src/modules/inventory/reports/fp-shiptment-delivery-buyer-report/service.js
src/routes/inventory.js
src/routes/production.js

add ui report shipment buyer delivery

add ui report shipment buyer delivery

---

src/modules/inventory/packing-receipt/data-form.html
src/modules/inventory/packing-receipt/data-form.js
src/modules/production/finishing-printing/packing/data-form.html
src/modules/production/finishing-printing/packing/data-form.js

update ui packing receipt & packing ui

update ui packing receipt & packing ui

---

src/modules/garment-purchasing/purchase-order-external/data-form.js

update purchase order external
add reset items

update purchase order external

---

src/modules/production/finishing-printing/quality-control/defect/data-form.html
src/modules/production/finishing-printing/quality-control/defect/data-form.js

update quality control add total amount table

update quality control

---

src/modules/inventory/packing-receipt/data-form.html
src/modules/inventory/packing-receipt/data-form.js
src/modules/inventory/packing-receipt/template/packing-item.js
src/modules/inventory/packing-receipt/view.js
src/modules/production/finishing-printing/packing/data-form.html
src/modules/production/finishing-printing/packing/data-form.js
src/modules/production/finishing-printing/packing/edit.js
src/modules/production/finishing-printing/packing/template/packing-item.js
src/modules/production/finishing-printing/packing/view.js
src/modules/purchasing/monitoring-purchase-request-all-unit/list.js
src/modules/purchasing/monitoring-purchase-request/list.js

update packing & packing receipt

---

src/modules/garment-purchasing/purchase-order-external-kasie/data-form.js
src/modules/garment-purchasing/purchase-order-external-kasie/template/purchase-order-external-item-header.html
src/modules/garment-purchasing/purchase-order-external-kasie/template/purchase-order-external-item.html
src/modules/garment-purchasing/purchase-order-external-over-budget/data-form.js
src/modules/garment-purchasing/purchase-order-external-over-budget/template/purchase-order-external-item-header.html
src/modules/garment-purchasing/purchase-order-external-over-budget/template/purchase-order-external-item.html
src/modules/garment-purchasing/purchase-order-external/data-form.js
src/modules/garment-purchasing/purchase-order-external/template/purchase-order-external-item-header.html
src/modules/garment-purchasing/purchase-order-external/template/purchase-order-external-item.html

1. Add Tipe Pembayaran (FREE) untuk Form PO External
2. Hapus Checklist Included PPN

Update Module UI - PO External

---

src/modules/garment-master-plan/weekly-plan/template/item.js

kurang ngasih setter ke dataAhTotal dan dataRemainingAH

Add setter to dataAhTotal and dataRemainingAH

---

src/modules/garment-purchasing/delivery-order/template/delivery-order-fulfillment.js
src/modules/garment-purchasing/purchase-order-external-over-budget/data-form.html
src/modules/garment-purchasing/purchase-order-external-over-budget/data-form.js
src/modules/garment-purchasing/purchase-order-external-over-budget/template/purchase-order-external-item-header.html
src/modules/garment-purchasing/purchase-order-external-over-budget/template/purchase-order-external-item-header.js
src/modules/garment-purchasing/purchase-order-external-over-budget/template/purchase-order-external-item.html
src/modules/garment-purchasing/purchase-order-external-over-budget/template/purchase-order-external-item.js
src/modules/garment-purchasing/purchase-order-external-over-budget/view.html
src/modules/garment-purchasing/purchase-order-external-over-budget/view.js

update ui delivery order,  purchase order over budget

update ui delivery order,  purchase order over budget

---

src/modules/garment-purchasing/delivery-order/template/delivery-order-fulfillment.js
src/modules/garment-purchasing/delivery-order/template/delivery-order-item-footer.html
src/modules/garment-purchasing/delivery-order/template/delivery-order-item-footer.js

update delivery order

---

src/modules/garment-purchasing/purchase-order-external/template/purchase-order-external-item.js
src/modules/garment-purchasing/purchase-price-correction/template/price-correction-item.js
src/modules/garment-purchasing/purchase-quantity-correction/template/purchase-quantity-correction-item.js
src/modules/garment-purchasing/unit-receipt-note/template/delivery-order-item.js

update ui po external, unit receipt, quality correction,price correction

update ui po external, unit receipt, quality correction,price correction

---

src/modules/garment-master-plan/weekly-plan/data-form.js
src/modules/garment-master-plan/weekly-plan/template/item.js

- Round ehTotal
- Set week readOnly when used in booking

Weekly Plan

---

src/routes/purchasing.js

Menambah Permission untuk monitoring SPB

Menambah Permission Monitoring SPB

---

src/modules/garment-master-plan/monitoring-remaining-eh/list.html
src/modules/garment-master-plan/monitoring-remaining-eh/list.js

- benerin auto sugestion tahun di monitoring remaining EH yang muncul terus setelah dipilih
- unit dikosongin jika year berubah

Fix Year Auto Sugestion on Monitoring Remaining EH

---

src/modules/garment-master-plan/sewing-blocking-plan/data-form.js
src/modules/garment-purchasing/monitoring-purchase-request/list.js
src/modules/production/spinning/spinning-input/create.js
src/modules/production/spinning/spinning-input/data-form.html
src/modules/production/spinning/spinning-input/data-form.js
src/modules/production/spinning/spinning-input/index.js
src/modules/production/spinning/spinning-input/service.js
src/modules/production/spinning/spinning-input/view.js
src/modules/production/spinning/yarn-output-production/view.js
src/modules/sales/finishing-printing-sales-contract/data-form.js

update spinning input

---

src/modules/production/spinning/spinning-input-report/index.html
src/modules/production/spinning/spinning-input-report/index.js
src/modules/production/spinning/spinning-input-report/list.html
src/modules/production/spinning/spinning-input-report/list.js
src/modules/production/spinning/spinning-input-report/service.js
src/modules/production/spinning/spinning-input/service.js
src/routes/spinning-production.js

spinning input report

---

src/modules/production/spinning/spinning-input/data-form.html
src/modules/production/spinning/spinning-input/data-form.js

update spinning input ui

---

src/modules/production/spinning/spinning-input-report/list.js
src/modules/production/spinning/spinning-input-report/service.js

update ui spinning

---

src/modules/purchasing/monitoring-surat-perintah-bayar/list.html
src/modules/purchasing/monitoring-surat-perintah-bayar/list.js
src/routes/purchasing.js

menambah field monitoring SPB untuk satuan , code supplier dan mata uang

MonitoringSPB

---

src/modules/production/spinning/spinning-input-report/list.js
src/modules/production/spinning/spinning-input-report/service.js
src/modules/production/spinning/spinning-input/data-form.js

update spinning report & spinning input

update spinning report & spinning input

---

src/modules/production/spinning/spinning-input-report/list.js
src/modules/production/spinning/spinning-input/create.js
src/modules/production/spinning/spinning-input/data-form.js
src/modules/production/spinning/spinning-input/list.js

update report spinning input. update colloums, add tofixed

update report spinning input. update colloums, add tofixed

---

src/modules/production/spinning/spinning-input-report/list.js
src/modules/production/spinning/spinning-input/data-form.js

update ui spinning input

---

src/modules/production/spinning/spinning-input-report/list.html
src/modules/production/spinning/spinning-input-report/list.js
src/modules/production/spinning/spinning-input-report/service.js
src/modules/production/spinning/spinning-input/create.html
src/modules/production/spinning/spinning-input/edit.html
src/modules/production/spinning/spinning-input/list.html
src/modules/production/spinning/spinning-input/list.js
src/modules/production/spinning/spinning-input/view.html
src/routes/spinning-production.js

update winder input prodcution

update winder input prodcution

---

src/modules/purchasing/purchase-request/data-form.html
src/modules/purchasing/purchase-request/data-form.js

update ui purchase request

---

src/modules/purchasing/monitoring-surat-perintah-bayar/list.html
src/modules/purchasing/monitoring-surat-perintah-bayar/list.js
src/routes/purchasing.js

Menambah Hak Akses pembukuan untuk Menu Koreksi Harga dan Koreksi Jumlah

Menambah Hak Akses

---

src/modules/production/finishing-printing/monitoring-event/data-form.html
src/modules/production/finishing-printing/monitoring-event/data-form.js
src/modules/production/finishing-printing/monitoring-event/edit.js
src/modules/production/finishing-printing/monitoring-event/service.js
src/modules/purchasing/purchase-request/create.js

update monitoring event

---

src/modules/garment-purchasing/customs/service.js
src/modules/garment-purchasing/customs/view.js

update ui customs

---

src/modules/garment-purchasing/delivery-order/create.js
src/modules/garment-purchasing/delivery-order/template/delivery-order-item.js

update delivery order garment

---

src/modules/purchasing/monitoring-surat-perintah-bayar/list.js
src/routes/purchasing.js

Update Monitoring SPB Jatuh Tempo dan Hak Akses

Update Monitoring SPB

---

src/modules/garment-purchasing/invoice-note/data-form.html
src/modules/garment-purchasing/invoice-note/data-form.js
src/modules/garment-purchasing/invoice-note/service.js
src/modules/production/finishing-printing/fp-retur-pro-inv-docs/data-form.html

update ui invoce & fp-retur-pro-inv-docs

update ui invoce & fp-retur-pro-inv-docs

---

src/modules/production/finishing-printing/fp-retur-pro-inv-docs/data-form.js
src/modules/production/finishing-printing/fp-retur-pro-inv-docs/template/detail.html
src/modules/production/finishing-printing/fp-retur-pro-inv-docs/template/detail.js

update fp retur pro inv docs

---

src/modules/garment-purchasing/invoice-note/data-form.html
src/modules/garment-purchasing/invoice-note/data-form.js
src/modules/garment-purchasing/invoice-note/template/invoice-note-fulfillment.js
src/modules/garment-purchasing/invoice-note/view.js

add recursive delete invoce

---

src/modules/garment-purchasing/invoice-note/create.js
src/modules/garment-purchasing/invoice-note/data-form.html
src/modules/garment-purchasing/invoice-note/data-form.js
src/modules/garment-purchasing/invoice-note/service.js
src/modules/garment-purchasing/invoice-note/view.js

update ui invoice

---

src/loader/garment-delivery-order-basic-loader.js
src/modules/garment-purchasing/invoice-note/data-form.html
src/modules/garment-purchasing/invoice-note/data-form.js
src/modules/garment-purchasing/invoice-note/template/invoice-note-item.html
src/modules/garment-purchasing/invoice-note/template/invoice-note-item.js

update invoice ui
add auto complte in collection

update invoice ui

---

src/modules/garment-purchasing/intern-note/create.js
src/modules/garment-purchasing/intern-note/data-form.html
src/modules/garment-purchasing/intern-note/data-form.js
src/modules/garment-purchasing/intern-note/template/intern-note-item.html
src/modules/garment-purchasing/intern-note/template/intern-note-item.js
src/modules/garment-purchasing/invoice-note/create.js
src/modules/garment-purchasing/invoice-note/data-form.js
src/modules/garment-purchasing/invoice-note/template/invoice-note-item.html

update ui note intern, invoice

update ui note intern, invoice

---

src/modules/garment-master-plan/monitoring-master-plan/fixed-columns/bootstrap-table-fixed-columns.css
src/modules/garment-master-plan/monitoring-master-plan/fixed-columns/bootstrap-table-fixed-columns.js
src/modules/garment-master-plan/monitoring-master-plan/list.html
src/modules/garment-master-plan/monitoring-master-plan/list.js

Tambahan masih dipakai di module direktori sendiri

Monitoring Master Plan :  Change to bootstrap-table and Add fixed columns

---

src/modules/production/finishing-printing/materials-request-note/data-form.js
src/modules/production/finishing-printing/materials-request-note/template/materials-request-note-item.html

Materials Request Note

---

src/modules/production/finishing-printing/fp-retur-pro-inv-docs/create.js
src/modules/production/finishing-printing/fp-retur-pro-inv-docs/data-form.html
src/modules/production/finishing-printing/fp-retur-pro-inv-docs/data-form.js
src/modules/production/finishing-printing/fp-retur-pro-inv-docs/template/detail.html
src/modules/production/finishing-printing/fp-retur-pro-inv-docs/template/detail.js
src/modules/production/finishing-printing/fp-retur-pro-inv-docs/view.js

update bon retur hasil regrading

update bon retur hasil regrading

---

src/modules/garment-purchasing/monitoring-kedatangan-barang/index.html
src/modules/garment-purchasing/monitoring-kedatangan-barang/index.js
src/modules/garment-purchasing/monitoring-kedatangan-barang/list.html
src/modules/garment-purchasing/monitoring-kedatangan-barang/list.js
src/modules/garment-purchasing/monitoring-kedatangan-barang/service.js
src/modules/garment-purchasing/monitoring-kedatangan-barang/view.html
src/modules/garment-purchasing/monitoring-kedatangan-barang/view.js
src/routes/garment-purchasing.js

Menambah menu monitoring ketepatan kedatangan barang dengan top ten supplier

menambah menu ketepatan kedatangan barang

---

src/modules/production/finishing-printing/fp-retur-pro-inv-docs/create.js
src/modules/production/finishing-printing/fp-retur-pro-inv-docs/data-form.html
src/modules/production/finishing-printing/fp-retur-pro-inv-docs/data-form.js
src/modules/production/finishing-printing/fp-retur-pro-inv-docs/list.js

update bon hasil re grading

---

src/modules/production/finishing-printing/fp-retur-pro-inv-docs/view.js

update ui bon re grading

---

src/modules/production/finishing-printing/daily-operation/template/bad-output-item.js

update daily operation

---

src/modules/garment-purchasing/monitoring-kedatangan-barang/service.js
src/modules/garment-purchasing/monitoring-pengiriman-barang/index.html
src/modules/garment-purchasing/monitoring-pengiriman-barang/index.js
src/modules/garment-purchasing/monitoring-pengiriman-barang/list.html
src/modules/garment-purchasing/monitoring-pengiriman-barang/list.js
src/modules/garment-purchasing/monitoring-pengiriman-barang/service.js
src/modules/garment-purchasing/monitoring-pengiriman-barang/view.html
src/modules/garment-purchasing/monitoring-pengiriman-barang/view.js
src/routes/garment-purchasing.js

menambah menu ketepatan pengiriman barang di garment purchase

ketepatan pengiriman barang

---

src/modules/production/finishing-printing/reports/monitoring-montly-operation-machine/list.js
src/modules/production/finishing-printing/reports/monitoring-montly-operation-machine/service.js

update monitoring montly operation

update monitoring montly operation

---

src/modules/production/finishing-printing/reports/monitoring-montly-operation-machine/list.js

update ui monitoring monthly operation machine

update ui monitoring monthly operation machine

---

src/modules/int-purchasing/external-transfer-order/create.js
src/modules/int-purchasing/external-transfer-order/data-form.html
src/modules/int-purchasing/external-transfer-order/edit.js
src/modules/int-purchasing/external-transfer-order/list.html
src/modules/int-purchasing/external-transfer-order/list.js
src/routes/int-purchasing.js

Set row green if IsPosted, Currency ke Mata Uang

DeliveryDate and OrderDate

---

src/modules/purchasing/monitoring-po-internal-belum-po-external/index.html
src/modules/purchasing/monitoring-po-internal-belum-po-external/index.js
src/modules/purchasing/monitoring-po-internal-belum-po-external/list.html
src/modules/purchasing/monitoring-po-internal-belum-po-external/list.js
src/modules/purchasing/monitoring-po-internal-belum-po-external/service.js
src/routes/purchasing.js

Add Route & Module - Monitring PO Internal Yang Belum Diproses Pembelian

Add Route & Module

---

src/modules/purchasing/monitoring-surat-perintah-bayar/list.html
src/modules/purchasing/monitoring-surat-perintah-bayar/list.js
src/modules/purchasing/monitoring-surat-perintah-bayar/service.js

UI Monitoring Surat Perintah Bayar

UI Monitoring Surat Perintah Bayar

---

src/modules/customs-report/cctv/list.html
src/modules/customs-report/cctv/list.js

Update Link menu CCTV untuk pengantian CCTV baru dengan link baru

Update Menu CCTV

---

src/modules/customs-report/cctv/list.html
src/modules/customs-report/cctv/list.js

Mengurangi menu link cctv beacukai , hanya 1 yang dibutuhkan

CCTV Beacukai

---

src/modules/verification/unit-payment-order-verification/create.js
src/modules/verification/unit-payment-order-verification/custom-dialog-view/alert-view.html
src/modules/verification/unit-payment-order-verification/custom-dialog-view/alert-view.js
src/modules/verification/unit-payment-order-verification/data-form.html
src/modules/verification/unit-payment-order-verification/data-form.js
src/modules/verification/unit-payment-order-verification/edit.html
src/modules/verification/unit-payment-order-verification/edit.js
src/modules/verification/unit-payment-order-verification/index.js
src/modules/verification/unit-payment-order-verification/monitoring-purchase.html
src/modules/verification/unit-payment-order-verification/monitoring-purchase.js
src/modules/verification/unit-payment-order-verification/service.js
src/modules/verification/unit-payment-order-verification/view.js

update verifcation  add monitoring purchase

---

src/modules/verification/unit-payment-order-verification/edit.js
src/modules/verification/unit-payment-order-verification/list.js

update verification ui

---

src/modules/garment-purchasing/purchase-order-external-kasie/data-form.html
src/modules/garment-purchasing/purchase-order-external-kasie/data-form.js
src/modules/garment-purchasing/purchase-order-external/data-form.html
src/modules/garment-purchasing/purchase-order-external/data-form.js
src/modules/master/garment-supplier-budgeting/data-form.html
src/modules/master/garment-supplier-budgeting/list.js
src/modules/master/garment-supplier/data-form.html
src/modules/master/garment-supplier/list.js

Modify Form PO External, filter supplier yang menggunakan PPN atau tidak menguunakan PPN, khsuusnya supplier lokal
Modify Garment Supplier, penambahan checklist Apakah Kena PPN ??, khususnya supplier lokal

Modify Form PO External & Form Garment Supplier

---

src/modules/purchasing/purchase-request/data-form.html

pull request paling keren abad ini

PR Date readonly after created

---

src/modules/master/product-budgeting/create.js
src/modules/master/product-budgeting/data-form.html
src/modules/master/product-budgeting/data-form.js
src/modules/master/product/data-form.html
src/modules/master/product/data-form.js
src/modules/sales/spinning-sales-contract/data-form.html
src/modules/sales/spinning-sales-contract/data-form.js
src/modules/sales/spinning-sales-contract/edit.js
src/modules/sales/spinning-sales-contract/view.js
src/modules/sales/weaving-sales-contract/data-form.html
src/modules/verification/unit-payment-order-verification/monitoring-purchase.html
src/modules/verification/unit-payment-order-verification/monitoring-purchase.js

update weaving , spinning

---

src/modules/master/product-budgeting/edit.js

update master product

---

src/loader/sp-master-plan-comodity-loader.js
src/main.js
src/modules/sp-master-plan/standard-hour/create.html
src/modules/sp-master-plan/standard-hour/create.js
src/modules/sp-master-plan/standard-hour/data-form.html
src/modules/sp-master-plan/standard-hour/data-form.js
src/modules/sp-master-plan/standard-hour/index.html
src/modules/sp-master-plan/standard-hour/index.js
src/modules/sp-master-plan/standard-hour/list.html
src/modules/sp-master-plan/standard-hour/list.js
src/modules/sp-master-plan/standard-hour/service.js
src/modules/sp-master-plan/standard-hour/view.html
src/modules/sp-master-plan/standard-hour/view.js
src/routes/index.js
src/routes/sp-master-plan.js
src/side-nav-bar.html

create sp master plan

---

src/main.js
src/modules/sales/spinning-sales-contract/data-form.js
src/modules/verification/unit-payment-order-verification/data-form.html

add uom unit bind

---

src/modules/verification/unit-payment-order-verification/data-form.html

update verification module

---

src/modules/verification/unit-payment-order-verification/data-form.html
src/modules/verification/unit-payment-order-verification/data-form.js
src/modules/verification/unit-payment-order-verification/edit.js
src/modules/verification/unit-payment-order-verification/monitoring-purchase.js
src/modules/verification/unit-payment-order-verification/view.js

update ui verification payment order

update ui verification payment order

---

src/modules/verification/unit-payment-order-verification/data-form.js
src/modules/verification/unit-payment-order-verification/list.js

Fix format number in Finance > VERIFIKASI SURAT PERINTAH BAYAR
/verification/unit-payment-order-verification

Change format number

---

src/modules/sales/reports/finishing-printing-sales-contract-report/list.html

menambahkan kolom untuk material dan kontruksi untuk melihat monitoring sales kontrak finishing printing

MonitoringSalesKontrakFinisingPrinting

---

src/modules/sales/reports/finishing-printing-sales-contract-report/list.html

Menambah Kolom No Benang dan Lebar Finish untuk menu laporan saleskontrakfinishingprinting

SalesContrakFinishingPrinting

---

src/modules/purchasing/unit-payment-price-correction-note/data-form.html
src/modules/purchasing/unit-payment-price-correction-note/data-form.js
src/modules/purchasing/unit-payment-price-correction-note/template/item.html
src/modules/purchasing/unit-payment-price-correction-note/template/item.js
src/modules/purchasing/unit-payment-quantity-correction-note/data-form.html
src/modules/purchasing/unit-payment-quantity-correction-note/data-form.js
src/modules/purchasing/unit-payment-quantity-correction-note/template/item.html
src/modules/purchasing/unit-payment-quantity-correction-note/template/item.js

unit-payment-price-correction-note and unit-payment-quantity-correction-note
reason: in new chrome remove function error (auto refresh)

Change from react to aurelia

---

src/modules/production/finishing-printing/kanban/template/step-item.js

add SelectedIndex StepItem

---

src/modules/production/finishing-printing/daily-operation/data-form.html
src/modules/production/finishing-printing/daily-operation/template/bad-output-item.html
src/modules/production/finishing-printing/daily-operation/template/bad-output-item.js
src/modules/production/finishing-printing/kanban/list.js
src/modules/production/finishing-printing/reports/monitoring-event-report/list.js

daily operation

---

src/modules/sales/production-order/data-form.html
src/modules/sales/production-order/data-form.js
src/modules/sales/production-order/edit.js
src/modules/sales/production-order/templates/detail-footer.html
src/modules/sales/production-order/view.js

update production order

---

src/modules/garment-purchasing/delivery-order/view.js

Hidden Tombol Ubah dan Hapus untuk menu Purchase Garment > Surat Jalan

PurchaseGarmentSuratJalan

---

src/modules/inventory/packing-receipt/data-form.html
src/modules/production/finishing-printing/monitoring-event/data-form.html
src/modules/production/finishing-printing/monitoring-event/data-form.js

update monitoring machine event. loader for machine event

update monitoring machine event. loader for machine event

---

src/modules/expedition/purchasing-document-acceptance/create.js
src/modules/expedition/purchasing-to-verification/templates/item.js
src/modules/verification/unit-payment-order-verification/monitoring-purchase.js

update ui, purchasing doc acceptan, verification, monitoring purchase

update ui, purchasing doc acceptan, verification, monitoring purchase

---

src/modules/garment-master-plan/booking-order-expired/data-form.html
src/modules/garment-master-plan/booking-order-expired/data-form.js
src/modules/garment-master-plan/booking-order-expired/detail.html
src/modules/garment-master-plan/booking-order-expired/detail.js
src/modules/garment-master-plan/booking-order-expired/index.html
src/modules/garment-master-plan/booking-order-expired/index.js
src/modules/garment-master-plan/booking-order-expired/list.html
src/modules/garment-master-plan/booking-order-expired/list.js
src/modules/garment-master-plan/booking-order-expired/service.js
src/modules/garment-master-plan/booking-order-expired/templates/booking-order-detail-footer.html
src/modules/garment-master-plan/booking-order-expired/templates/booking-order-detail-footer.js
src/modules/garment-master-plan/booking-order-expired/templates/booking-order-detail-header.html
src/modules/garment-master-plan/booking-order-expired/templates/booking-order-detail-header.js
src/modules/garment-master-plan/booking-order-expired/templates/booking-order-detail.html
src/modules/garment-master-plan/booking-order-expired/templates/booking-order-detail.js
src/modules/garment-master-plan/booking-order-expired/view.html
src/modules/garment-master-plan/booking-order-expired/view.js
src/modules/garment-master-plan/booking-order/list.js
src/modules/garment-master-plan/booking-order/view.js
src/routes/garment-master-plan.js

Update juga logic status Expired di Booking Order Menu

Add Expired Booking Order Menu

---

src/loader/garment-delivery-order-loader.js
src/modules/garment-purchasing/monitoring-delivery-order-new/index.html
src/modules/garment-purchasing/monitoring-delivery-order-new/index.js
src/modules/garment-purchasing/monitoring-delivery-order-new/list.html
src/modules/garment-purchasing/monitoring-delivery-order-new/list.js
src/modules/garment-purchasing/monitoring-delivery-order-new/service.js
src/routes/garment-purchasing.js

Menambahkan Menu Monitoring Delivery Order

Monitoring Delivery Order

---

src/modules/weaving/order/data-form.html
src/modules/weaving/order/data-form.js

- add periodeBulan on SOP UI
- add periodeTahun on SOP UI

Weaving (SOP UI & MKB UI)

---

src/modules/purchasing/monitoring-price/index.html
src/modules/purchasing/monitoring-price/index.js
src/modules/purchasing/monitoring-price/list.html
src/modules/purchasing/monitoring-price/list.js
src/modules/purchasing/monitoring-price/service.js
src/routes/purchasing.js

Update Module Monitoring Price

Update Module Monitoring Price

---

package-lock.json
package.json

aurelia-loader-webpack: 1.0.3
- aurelia-loader: 1.0.0
https://github.com/danliris/dl-ui/issues/1978

aurelia-loader:1.0.0

---

src/modules/garment-purchasing/reports/supplier-report/index.html
src/modules/garment-purchasing/reports/supplier-report/index.js
src/modules/garment-purchasing/reports/supplier-report/list.html
src/modules/garment-purchasing/reports/supplier-report/list.js
src/modules/garment-purchasing/reports/supplier-report/service.js
src/routes/garment-purchasing.js

Add Route  Lap. Total Pembelian Garment
Add Module  Lap. Total Pembelian Garment

Add Route & Module - Lap. Total Pembelian Garment

---

src/modules/weaving/master-fabric-construction/create.js
src/modules/weaving/master-fabric-construction/edit.js
src/modules/weaving/master-yarn/data-form.html
src/modules/weaving/master-yarn/data-form.js
src/modules/weaving/master-yarn/edit.js
src/modules/weaving/order-production-report/service.js
src/modules/weaving/order-production/create.js
src/modules/weaving/order-production/data-form.html
src/modules/weaving/order-production/data-form.js
src/modules/weaving/order-production/list.js
src/modules/weaving/order-production/service.js
src/modules/weaving/order-production/view.js

Weaving UI Order Production

---

src/modules/weaving/order-production/data-form.js
src/modules/weaving/order-production/edit.js

Dev - Weaving UI Order Production

---

src/modules/weaving/master-fabric-construction/create.js
src/modules/weaving/master-fabric-construction/data-form.js
src/modules/weaving/master-fabric-construction/edit.js
src/modules/weaving/master-material-type/create.js
src/modules/weaving/master-material-type/edit.js
src/modules/weaving/master-ring/create.js
src/modules/weaving/master-ring/edit.js
src/modules/weaving/master-supplier/create.js
src/modules/weaving/master-supplier/edit.js
src/modules/weaving/master-yarn/create.js
src/modules/weaving/master-yarn/data-form.js
src/modules/weaving/master-yarn/edit.js
src/modules/weaving/order-production/data-form.js
src/modules/weaving/order-production/edit.js

- changes on master material's validation
- changes on master ring's validation
- changes on master supplier's validation
- changes on master yarn's validation
- changes on master fabric construction's validation

Weaving UI Validation on Master

---

src/modules/purchasing/monitoring-surat-perintah-bayar-new/index.html
src/modules/purchasing/monitoring-surat-perintah-bayar-new/index.js
src/modules/purchasing/monitoring-surat-perintah-bayar-new/list.html
src/modules/purchasing/monitoring-surat-perintah-bayar-new/list.js
src/modules/purchasing/monitoring-surat-perintah-bayar-new/service.js
src/routes/purchasing.js

Menambahkan menu Surat Perintah Bayar

Monitoring Surat Perintah Bayar

---

src/modules/weaving/estimated-production/create.js
src/modules/weaving/estimated-production/data-form.html
src/modules/weaving/estimated-production/data-form.js
src/modules/weaving/estimated-production/edit.js
src/modules/weaving/estimated-production/list.js
src/modules/weaving/estimated-production/templates/items.js
src/modules/weaving/estimated-production/view.js
src/modules/weaving/master-fabric-construction/data-form.html
src/modules/weaving/master-fabric-construction/data-form.js
src/modules/weaving/master-material-type/create.js

- change loader properties bind on master fabric constructions (code to name)

Weaving UI Master Fabric Constructions

---

src/modules/purchasing/generating-data/list.html
src/modules/purchasing/generating-data/list.js
src/modules/purchasing/generating-data/service.js
src/routes/purchasing.js

Add Module - Generate Data textile Purchasing

Add Module - Generate Data textile Purchasing

---

src/modules/purchasing/koreksi-jumlah/index.html
src/modules/purchasing/koreksi-jumlah/index.js
src/modules/purchasing/koreksi-jumlah/list.html
src/modules/purchasing/koreksi-jumlah/list.js
src/modules/purchasing/koreksi-jumlah/service.js
src/routes/purchasing.js

Menambahkan menu monitoring Koreksi Jumlah di menu Purchase textile

Monitoring Koreksi Jumlah ( Purchase )

---

src/modules/weaving/master-yarn-number/list.js
src/modules/weaving/master-yarn-origin/data-form.html
src/modules/weaving/master-yarn-origin/edit.js
src/modules/weaving/master-yarn/create.js
src/modules/weaving/master-yarn/data-form.html
src/modules/weaving/master-yarn/data-form.js
src/modules/weaving/master-yarn/edit.js
src/modules/weaving/order-production/create.js

Master Asal Benang
· Perubahan pada urutan fieldnya
§ Nama Asal benang
§ Kode Asal benang
Master Benang
· Kode Benang terisi otomatis dari field ‘kode material’ + ‘kode nomor benang’

update from revisi mom 13 maret 2019

---

src/modules/weaving/estimated-production/data-form.html
src/modules/weaving/estimated-production/data-form.js
src/modules/weaving/master-fabric-construction/create.js
src/modules/weaving/master-fabric-construction/data-form.html
src/modules/weaving/master-fabric-construction/data-form.js
src/modules/weaving/master-fabric-construction/edit.js
src/modules/weaving/master-fabric-construction/templates/items-warp.html
src/modules/weaving/master-fabric-construction/templates/items-warp.js
src/modules/weaving/master-fabric-construction/templates/items-weft.html
src/modules/weaving/master-fabric-construction/templates/items-weft.js
src/modules/weaving/master-fabric-construction/view.js
src/modules/weaving/order-production/create.js
src/modules/weaving/order-production/data-form.html
src/modules/weaving/order-production/edit.js
src/modules/weaving/order-production/list.js

update construction, sop and etc for validation and enhancement from mom 13 maret 2019

Bugfix and enhancement for weaving

---

src/modules/garment-purchasing/monitoring-delivery-order-new/list.js

Add Column  (Staf Pembelian P/O, No Bon Unit, Tgl Bon, Unit) di Monitoring Surat Jalan Garment

Update Module : Monitoring Surat Jalan Garment

---

src/main.js
src/modules/weaving/master-fabric-construction/data-form.js
src/modules/weaving/master-fabric-construction/edit.js

Weaving UI Endpoint

---

src/main.js
src/modules/purchasing/monitoring-purchase-order-all-user/list.html
src/modules/purchasing/monitoring-purchase-order/list.html
src/routes/garment-purchasing.js
src/routes/purchasing.js

Update monitoring purchase

---

src/modules/garment-purchasing/monitoring-kedatangan-barang/view.js

Untuk menu detail tarik excel tadinya lum bisa jalan , ubah agar bisa jalan tarik excel nya

Monitoring Ketepatan Kedatangan

---

src/modules/weaving/daily-operational-machine-input/create.js
src/modules/weaving/daily-operational-machine-input/data-form.html
src/modules/weaving/daily-operational-machine-input/data-form.js
src/modules/weaving/daily-operational-machine-input/list.js
src/modules/weaving/daily-operational-machine-input/service.js
src/modules/weaving/daily-operational-machine-input/templates/items.html
src/modules/weaving/daily-operational-machine-input/templates/items.js
src/modules/weaving/order-production-report/list.js
src/modules/weaving/weaving-efficiency-report/index.html
src/modules/weaving/weaving-efficiency-report/index.js
src/modules/weaving/weaving-efficiency-report/list.html
src/modules/weaving/weaving-efficiency-report/list.js
src/modules/weaving/weaving-efficiency-report/service.js
src/routes/weaving.js

- switch field position on daily operational machine data-form (shift & machine)

Weaving UI Daily Operational Machine

---

src/modules/purchasing/reports/purchase-order-report/staff-report-new/index.html
src/modules/purchasing/reports/purchase-order-report/staff-report-new/index.js
src/modules/purchasing/reports/purchase-order-report/staff-report-new/list.html
src/modules/purchasing/reports/purchase-order-report/staff-report-new/list.js
src/modules/purchasing/reports/purchase-order-report/staff-report-new/service.js
src/modules/purchasing/reports/purchase-order-report/staff-report-new/view.html
src/modules/purchasing/reports/purchase-order-report/staff-report-new/view.js
src/routes/purchasing.js

Menitoring Ketepatan kedatangan per Staff untuk sasaran mutu pembelian textile

Menitoring Ketepatan kedatangan per Staff

---

src/main.js
src/modules/garment-purchasing/reports/supplier-report/list.html
src/modules/garment-purchasing/reports/supplier-report/list.js
src/modules/garment-purchasing/reports/supplier-report/service.js
src/modules/purchasing/monitoring-po-internal-belum-po-external/list.html
src/modules/purchasing/monitoring-po-internal-belum-po-external/list.js
src/modules/purchasing/monitoring-po-internal-belum-po-external/service.js
src/routes/purchasing.js

Add Module | PO Internal Yang Belum Dibuat PO External
Add Route | PO Internal Yang Belum Dibuat PO External

Add Modul | PO Internal Yang Belum Dibuat PO External

---

src/modules/weaving/daily-operation-loom/list.js
src/modules/weaving/daily-operation-loom/template/finish-form.js
src/modules/weaving/daily-operation-loom/template/resume-form.js
src/modules/weaving/daily-operation-loom/template/stop-form.js
src/modules/weaving/daily-operation-loom/update.js

 Bug Fix, loom

---

src/modules/accounting/reports/central-bill-reception-report/index.html
src/modules/accounting/reports/central-bill-reception-report/index.js
src/modules/accounting/reports/central-bill-reception-report/list.html
src/modules/accounting/reports/central-bill-reception-report/list.js
src/modules/accounting/reports/central-bill-reception-report/service.js
src/routes/accounting.js

Add Route & Module - Report Penerimaan Bon Pusat | Accounting

Add Route & Module - Report Penerimaan Bon Pusat

---

src/modules/accounting/reports/central-bill-expenditure-report/index.html
src/modules/accounting/reports/central-bill-expenditure-report/index.js
src/modules/accounting/reports/central-bill-expenditure-report/list.html
src/modules/accounting/reports/central-bill-expenditure-report/list.js
src/modules/accounting/reports/central-bill-expenditure-report/service.js
src/routes/accounting.js

Add Form & Routes  Monitoring Pengeluaran Bon Pusat

Add Form & Routes Monitoring Pengeluaran Bon Pusat

---

src/modules/weaving/master-material-type/data-form.js
src/modules/weaving/master-material-type/templates/items.html
src/modules/weaving/master-material-type/templates/items.js
src/modules/weaving/master-yarn-number/create.js
src/modules/weaving/master-yarn-number/edit.js

1. master yarn
2. fix master material type when on new yarn number flow

fix bug on

---

src/modules/accounting/reports/correction-note-reception-report/index.html
src/modules/accounting/reports/correction-note-reception-report/index.js
src/modules/accounting/reports/correction-note-reception-report/list.html
src/modules/accounting/reports/correction-note-reception-report/list.js
src/modules/accounting/reports/correction-note-reception-report/service.js
src/routes/accounting.js

1. Add Form | Monitoring Penerimaan Nota Koreksi
2. Add Route | Monitoring Penerimaan Nota Koreksi

Add Form | Monitoring Penerimaan Nota Koreksi

---

src/modules/purchasing/monitoring-purchase-order-all-user/list.js
src/modules/purchasing/monitoring-purchase-order/list.js

add division loader monitoring-purchase & monitoring-purchase-all

Update division filter

---

src/modules/accounting/reports/central-bill-expenditure-report/list.html
src/modules/accounting/reports/central-bill-expenditure-report/list.js
src/modules/accounting/reports/central-bill-reception-report/list.html
src/modules/accounting/reports/central-bill-reception-report/list.js
src/modules/accounting/reports/correction-note-reception-report/list.html
src/modules/accounting/reports/correction-note-reception-report/list.js

Report Penerimaan Bon Pusat
Report Pengeluaran Bon Pusat
Report Peneriman Nota Koreksi

Update UI - Report

---

src/modules/accounting/reports/flow-penerimaan/index.html
src/modules/accounting/reports/flow-penerimaan/index.js
src/modules/accounting/reports/flow-penerimaan/list.html
src/modules/accounting/reports/flow-penerimaan/list.js
src/modules/accounting/reports/flow-penerimaan/service.js
src/routes/accounting.js

tambah menu flow detail penerimaan untuk accounting

Menu Flor Detail Penerimaan

---

src/modules/accounting/reports/correction-note-expenditure-report/index.html
src/modules/accounting/reports/correction-note-expenditure-report/index.js
src/modules/accounting/reports/correction-note-expenditure-report/list.html
src/modules/accounting/reports/correction-note-expenditure-report/list.js
src/modules/accounting/reports/correction-note-expenditure-report/service.js
src/routes/accounting.js

Add Module & Route | Laporan Pengeluaran Nota Koreksi

Add Module & Route | Laporan Pengeluaran Nota Koreksi
